// <auto-generated />
using System;
using MattsRestaurant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MattsRestaurant.Migrations
{
    [DbContext(typeof(DinnerDbContext))]
    partial class DinnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MattsRestaurant.Models.Dinner", b =>
                {
                    b.Property<int>("DinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Allergens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CuisineType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinnerCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DinnerOfTheDay")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("DinnerId");

                    b.ToTable("dinners");

                    b.HasData(
                        new
                        {
                            DinnerId = 1,
                            Allergens = "Gluten, Eggs, Lactose, Soybeans",
                            CuisineType = 0,
                            Description = "Type of pizza with ham, mushroom and tomatos",
                            DinnerCategory = "FastFood",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/PizzaCapriciosa.png",
                            Name = "Pizza Capriciosa",
                            Price = 19.199999999999999
                        },
                        new
                        {
                            DinnerId = 2,
                            Allergens = "Gluten, Lactose",
                            CuisineType = 4,
                            Description = "A long piece of wood or metal used for holding pieces of food, typically meat, together during cooking",
                            DinnerCategory = "Barbeque foods",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/Skewers.png",
                            Name = "Skewers",
                            Price = 10.0
                        },
                        new
                        {
                            DinnerId = 3,
                            Allergens = "Gluten, Lactose, Soyabeans, Eggs",
                            CuisineType = 1,
                            Description = @"Sticky dough with stuffing inside.
Types: Russia, With meat, sweets, with blueberries, with spinach",
                            DinnerCategory = "Cake Dinner",
                            DinnerOfTheDay = true,
                            ImageUrl = "~/images/Dumplings.png",
                            Name = "Dumplings",
                            Price = 9.0
                        },
                        new
                        {
                            DinnerId = 4,
                            Allergens = "Eggs, Milk, Celary, Mustard",
                            CuisineType = 2,
                            Description = "A Japanese dish consisting of small balls or rolls of vinegar-flavoured cold rice served with a garnish of vegetables, egg, or raw seafood.",
                            DinnerCategory = "Japanesse Kitchen",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/Sushi.png",
                            Name = "Japanesse Sushi",
                            Price = 18.0
                        },
                        new
                        {
                            DinnerId = 5,
                            Allergens = "Gluten, Milk, Lactose, Eggs",
                            CuisineType = 0,
                            Description = "An Italian dish consisting of lasagne baked with meat or vegetables and a cheese sauce.",
                            DinnerCategory = "Baked Dishes",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/Lasagne.png",
                            Name = "Lasagne Bolognesse",
                            Price = 12.0
                        },
                        new
                        {
                            DinnerId = 6,
                            Allergens = "Gluten, Eggs, Lactose",
                            CuisineType = 1,
                            Description = "Chicken breasts stuffed with cheese, butter and spinnach",
                            DinnerCategory = "Main Dishes",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/De volaille.png",
                            Name = "De voliaille",
                            Price = 18.0
                        },
                        new
                        {
                            DinnerId = 7,
                            Allergens = "Gluten, Eggs, Lactose",
                            CuisineType = 0,
                            Description = "Pesto has become a catch all word used to describe many different things today. It originated in Italy as a mortar-and-pestle ground, coarse sauce made of basil, pine nuts, garlic, Parmesan, and olive oil. ",
                            DinnerCategory = "Italian Food",
                            DinnerOfTheDay = false,
                            ImageUrl = "~/images/Basil Pesto.png",
                            Name = "Basil Pesto",
                            Price = 22.0
                        });
                });

            modelBuilder.Entity("MattsRestaurant.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("timeToPlaced")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MattsRestaurant.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("DinnerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("DinnerId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MattsRestaurant.Models.ShoppingCart", b =>
                {
                    b.Property<int>("cartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("DinnerId")
                        .HasColumnType("int");

                    b.Property<string>("cartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cartItemId");

                    b.HasIndex("DinnerId");

                    b.ToTable("shoppingCarts");
                });

            modelBuilder.Entity("MattsRestaurant.Models.OrderDetail", b =>
                {
                    b.HasOne("MattsRestaurant.Models.Dinner", "Dinner")
                        .WithMany()
                        .HasForeignKey("DinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MattsRestaurant.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MattsRestaurant.Models.ShoppingCart", b =>
                {
                    b.HasOne("MattsRestaurant.Models.Dinner", "dinner")
                        .WithMany()
                        .HasForeignKey("DinnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
